// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240812230222_Wissto")]
    partial class Wissto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Core.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Owner");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2188b73c-33ae-459f-98ff-bf65fe58ffdc"),
                            Avatar = "avatar.jpg",
                            FullName = "Wissem Hmidi",
                            Profil = "Software Developer in C#"
                        });
                });

            modelBuilder.Entity("Core.Entities.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("620fffd2-3b41-4769-ac38-eaf339435438"),
                            Description = "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum magnis justo primis ligula facilisi non torquent pulvinar. Tellus tortor morbi ullamcorper sagittis proin quam. Parturient Lacinia blandit rutrum; turpis elit taciti dignissim suspendisse. Quis gravida curae, tellus vulputate urna venenatis. Nisl viverra curabitur a pretium suscipit.",
                            ImageUrl = "cake.png",
                            ProjectName = "Project Alpha"
                        },
                        new
                        {
                            Id = new Guid("38c8d58e-fc07-449b-9298-5bd4ded8bc60"),
                            Description = "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
                            ImageUrl = "circus.png",
                            ProjectName = "Project Beta"
                        },
                        new
                        {
                            Id = new Guid("34b34fbf-4e4e-42b1-ab71-f4915e2ebe84"),
                            Description = "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.",
                            ImageUrl = "safe.png",
                            ProjectName = "Project Gamma"
                        },
                        new
                        {
                            Id = new Guid("f876025d-db45-40f5-bf1b-66cc63b46334"),
                            Description = "Curabitur gravida arcu ac tortor dignissim convallis. Aenean et tortor at risus viverra adipiscing at in tellus.",
                            ImageUrl = "submarine.png",
                            ProjectName = "Project Delta"
                        });
                });

            modelBuilder.Entity("Core.Entities.Owner", b =>
                {
                    b.HasOne("Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
